# Generated by Django 3.2.25 on 2024-03-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240229_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedDrinksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.JSONField()),
            ],
        ),
    ]
