# Generated by Django 3.2.25 on 2024-03-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_saveddrinkslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='flavorProfileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinks', models.JSONField()),
            ],
        ),
    ]
